server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/access;DB_CLOSE_DELAY=-1
    username: access
    password:
      driver-class: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

camunda.bpm.admin-user:
  id: demo
  password: demo
  first-name: Demo
  last-name: Demo


